In [11]:
import pandas as pd

In [12]:
dataset = pd.read_csv("general_data.csv")

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
dataset.Attrition = le.fit_transform(dataset.Attrition)
dataset.BusinessTravel  = le.fit_transform(dataset.BusinessTravel)
dataset.Department  = le.fit_transform(dataset.Department)
dataset.EducationField  = le.fit_transform(dataset.EducationField)
dataset.JobRole  = le.fit_transform(dataset.JobRole)
dataset.Gender  = le.fit_transform(dataset.Gender)
dataset['Over18'] = le.fit_transform(dataset.Over18)
dataset.MaritalStatus  = le.fit_transform(dataset.MaritalStatus)
s=[]
r=[]
dataset.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,0,2,2,6,2,1,1,1,0,...,1.0,0,11,8,0,1.0,6,1,0,0
1,31,1,1,1,10,1,1,1,2,0,...,0.0,0,23,8,1,6.0,3,5,1,4
2,32,0,1,1,17,4,4,1,3,1,...,1.0,0,15,8,3,5.0,2,5,0,3
3,38,0,0,1,2,5,1,1,4,1,...,3.0,0,11,8,3,13.0,5,8,7,5
4,32,0,2,1,10,1,3,1,5,1,...,4.0,0,12,8,2,9.0,2,6,0,4

In [5]:
dataset.isna().sum()

Age                         0
Attrition                   0
BusinessTravel              0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeID                  0
Gender                      0
JobLevel                    0
JobRole                     0
MaritalStatus               0
MonthlyIncome               0
NumCompaniesWorked         19
Over18                      0
PercentSalaryHike           0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           9
TrainingTimesLastYear       0
YearsAtCompany              0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [14]:
dataset = dataset.fillna(method='bfill')
dataset = dataset.fillna(method='ffill')
dataset.isna().sum()

Age                        0
Attrition                  0
BusinessTravel             0
Department                 0
DistanceFromHome           0
Education                  0
EducationField             0
EmployeeCount              0
EmployeeID                 0
Gender                     0
JobLevel                   0
JobRole                    0
MaritalStatus              0
MonthlyIncome              0
NumCompaniesWorked         0
Over18                     0
PercentSalaryHike          0
StandardHours              0
StockOptionLevel           0
TotalWorkingYears          0
TrainingTimesLastYear      0
YearsAtCompany             0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64

In [15]:
y = dataset.Attrition
x = dataset[['Age','BusinessTravel','Department','DistanceFromHome','Education','EducationField','EmployeeCount','EmployeeID','Gender','JobLevel','JobRole','MaritalStatus','MonthlyIncome','PercentSalaryHike','StandardHours','TrainingTimesLastYear','YearsAtCompany','YearsSinceLastPromotion','YearsWithCurrManager']]

In [21]:
import statsmodels.api as sm
x1 = sm.add_constant(x)

In [22]:
Logistic = sm.Logit(y,x1)

In [23]:
result = Logistic.fit()
result.summary()

Optimization terminated successfully.
         Current function value: 0.399005
         Iterations 7

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:              Attrition   No. Observations:                 4410
Model:                          Logit   Df Residuals:                     4392
Method:                           MLE   Df Model:                           17
Date:                Fri, 21 Aug 2020   Pseudo R-squ.:                 0.09665
Time:                        11:11:17   Log-Likelihood:                -1759.6
converged:                       True   LL-Null:                       -1947.9
Covariance Type:            nonrobust   LLR p-value:                 1.480e-69
===========================================================================================
                              coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
Age                        -0.0404      0.005     -7.734      0.000      -0.051      -0.030
BusinessTravel             -0.0299      0.065     -0.459      0.646      -0.157       0.098
Department                 -0.2220      0.080     -2.767      0.006      -0.379      -0.065
DistanceFromHome           -0.0006      0.005     -0.119      0.905      -0.011       0.010
Education                  -0.0647      0.042     -1.537      0.124      -0.147       0.018
EducationField             -0.1020      0.033     -3.074      0.002      -0.167      -0.037
EmployeeCount               0.0067   1.01e+07    6.6e-10      1.000   -1.98e+07    1.98e+07
EmployeeID              -6.951e-06   3.37e-05     -0.206      0.837   -7.31e-05    5.92e-05
Gender                      0.0604      0.089      0.681      0.496      -0.113       0.234
JobLevel                   -0.0244      0.039     -0.623      0.534      -0.101       0.052
JobRole                     0.0357      0.018      2.011      0.044       0.001       0.070
MaritalStatus               0.5684      0.063      9.074      0.000       0.446       0.691
MonthlyIncome           -2.078e-06   9.56e-07     -2.175      0.030   -3.95e-06   -2.05e-07
PercentSalaryHike           0.0149      0.012      1.271      0.204      -0.008       0.038
StandardHours               0.0533   1.26e+06   4.22e-08      1.000   -2.48e+06    2.48e+06
TrainingTimesLastYear      -0.1416      0.035     -4.036      0.000      -0.210      -0.073
YearsAtCompany             -0.0363      0.016     -2.292      0.022      -0.067      -0.005
YearsSinceLastPromotion     0.1333      0.020      6.549      0.000       0.093       0.173
YearsWithCurrManager       -0.1381      0.022     -6.323      0.000      -0.181      -0.095
===========================================================================================
"""

1. Age,MaritalStatus,TrainingTimesLastYear,YearsSinceLastPromotion,YearsWithCurrManager are most significant for attrition
2. P value 0.86 is greater then 0.05 so the probibality of attrition is more